language: groovy

jdk:
    - oraclejdk7

before_install:
    - mkdir -p ~/.m2
    - bash -c '{ curl http://files.thehyve.net/caches/grails_2.3.5_mvncache.tar.gz  | tar -C ~/.m2 -xzf -; } || true'
    - git clone --depth 1 git://github.com/thehyve/transmart-travis.git ~/ts-travis
    - source ~/ts-travis/init.sh
    - source ~/ts-travis/grails_inline.sh
    - source ~/ts-travis/maven_dep.sh
    - mkdir -p ~/.grails/transmartConfig
    - cp .travis.BuildConfig.groovy ~/.grails/transmartConfig/BuildConfig.groovy

install:
    - maybe_build_maven_dep $(travis_get_owner)/transmart-core-api core-api
    - maybe_make_inline_grails_dep $(travis_get_owner)/transmart-core-db core-db . transmart-core-db-tests
    - maybe_make_inline_grails_dep $(travis_get_owner)/Rmodules Rmodules
    - maybe_make_inline_grails_dep $(travis_get_owner)/transmart-gwas-plugin transmart-gwas
    - maybe_make_inline_grails_dep $(travis_get_owner)/folder-management-plugin folder-management
    - maybe_make_inline_grails_dep $(travis_get_owner)/transmart-extensions transmart-extensions transmart-java search-domain biomart-domain
    - maybe_make_inline_grails_dep $(travis_get_owner)/transmart-rest-api transmart-rest-api
    - maybe_make_inline_grails_dep $(travis_get_owner)/blend4j-plugin blend4j-plugin
    - maybe_make_inline_grails_dep $(travis_get_owner)/transmart-metacore-plugin transmart-metacore-plugin

script:
    - grails refresh-dependencies --non-interactive
    - grails test-app --non-interactive --stacktrace
    - grails war

deploy:
  provider: releases
  api_key:
    secure: PrAa8dbmMsU3pWLiXhgD+ILuBxG40JT+jdDGwTWrsqSbtitYSBGQvXpNchSn2lfrUjlYP0Fl6NolykR0MNqRDj9bT3RbACenuf5ajJiixh8zdIuZOsflAG4lWLij/Rp99SEcv949Uvz1MPQggtorvETGtRtiApwQsSXeeZiJkmY=
  file: target/transmart.war
  on:
    repo: biogen-tm/transmartApp
    branch: release-1.2.3.biogen
    all_branches: true

